# syntax=docker/dockerfile:1.5

FROM node:current-alpine3.21 AS build 

WORKDIR /usr/src/app

COPY package*.json ./

RUN --mount=type=cache,target=/usr/src/app/.npm \
    npm set cache /usr/src/app/.npm && \
    npm install

COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev"]


