services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /usr/src/app
          ignore:
            - node_modules/**
    restart: always
    environment:
      - VITE_APP_BACKEND_ADDRESS=http://localhost/api
    networks:
      - network
    ports:
      - 5173:5173
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    develop:
      watch:
        - action: sync
          path: ./backend/app
          target: /api/app
    restart: always
    env_file: ".env"
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - INSTANCE_CONNECTION_NAME=${INSTANCE_CONNECTION_NAME}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
    networks:
      - network
    ports:
      - 8080:8080
  tests:
    build:
      context: ./backend
      dockerfile: Dockerfile.test
    container_name: backend-tests
    env_file: ".env"
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}_test
      - INSTANCE_CONNECTION_NAME=${INSTANCE_CONNECTION_NAME}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
      - PYTHONPATH=/api
    networks:
      - network
    volumes:
      - ./backend/app:/api/app
      - ./backend/tests:/api/tests
networks:
  network:
