[tool.poetry]
name = "smart-energy-backend"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{include = "smart_energy_backend"}]

[tool.poetry.dependencies]
python = "^3.9"
uvicorn = "^0.34.0"
fastapi = "^0.115.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
